### ISSUE TITLE
Proposal: is it possible to put it it on https://www.libhunt.com?

### ISSUE THREAD

**Issue by edl7878** [bodiam/awesome-asciidoc#10]
I used to use https://go.libhunt.com/ to find anything new with golang.

I think awesome-asciidoc is cool, and if it is available on libhunt, that would be AWESOME!

**Comment by bodiam** [comment]
Hi @edl7878 , maybe, but this has hardly anything to do with golang right? Closing for now, but if I'm missing something, please let me know!

**Comment by edl7878** [comment]
This is the libhunt awesome list:

https://www.libhunt.com/

I think asciidoc should be on the list. :)
