### ISSUE TITLE
could goasciidoc - golang ascidoc generator qualify?

### ISSUE THREAD

**Issue by mariotoffia** [bodiam/awesome-asciidoc#8]
the [goasciidoc](https://github.com/mariotoffia/goasciidoc) is in early stages but is a asciidoc generator from golang code - completely template driven.

**Comment by bodiam** [comment]
Sure! Can you do a PR so I can add it? Thanks for the tip!

**Comment by mariotoffia** [comment]
Sure I'll do it right away.

Cheers,
 Mario
